USE [master]
GO

/****** Object:  Database [UDB]    Script Date: 7/12/2021 09:20:34 ******/
CREATE DATABASE [UDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\UDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'UDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\UDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [UDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [UDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [UDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [UDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UDB] SET RECOVERY FULL 
GO

ALTER DATABASE [UDB] SET  MULTI_USER 
GO

ALTER DATABASE [UDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [UDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [UDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [UDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [UDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [UDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [UDB] SET  READ_WRITE 
GO

