//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAS.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrera
    {
        public int idCarrera { get; set; }
        public string nameCarrera { get; set; }
        public string objetivoCarrera { get; set; }
        public string perfilEgresoCarrera { get; set; }
        public string areaDesempenoCarrera { get; set; }
        public string pensumCarrera { get; set; }
        public int tipoCarrera { get; set; }
    
        public virtual Tipo Tipo { get; set; }
    }
}
