//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAS.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulta
    {
        public int idConsulta { get; set; }
        public string tipoConsulta { get; set; }
        public string correoConsulta { get; set; }
        public string contenidoConsulta { get; set; }
        public string Nombre { get; set; }
    }
}
